// Data kelas ampuan — Dimas Bagus Nurdiansyah, S.Kom.
// Mapel Informatika & Koding dan Kecerdasan Artifisial (KKA)
// Demo Sekolah — Tahun Ajaran Sekarang
const DATAKELAS_DATA = [
  {
    "kelas": "XI - 7",
    "siswa": [
      {"no": 1, "nama": "ADITYA PRATAMA KUSUMA"},
      {"no": 2, "nama": "AGNES PUTRI RAMADHANI"},
      {"no": 3, "nama": "AISYAH PUTRI RAMADHANI"},
      {"no": 4, "nama": "ALDI PRANATA WIJAYA"},
      {"no": 5, "nama": "ALIF FADHILAH RAHMAT"},
      {"no": 6, "nama": "ALMA SYAKIRA AZZAHRA"},
      {"no": 7, "nama": "ARDIANSYAH PUTRA WIJAYA"},
      {"no": 8, "nama": "BAGAS PRAYOGA UTAMA"},
      {"no": 9, "nama": "BAYU AJI NUGROHO"},
      {"no": 10, "nama": "BELLA AMALIA PUTRI"},
      {"no": 11, "nama": "BERLIAN RAMADHANI PUTRI"},
      {"no": 12, "nama": "BIMA SAKTI PRATAMA"},
      {"no": 13, "nama": "BRIGITTA KIRANA PUTRI"},
      {"no": 14, "nama": "BRYAN ALVARO PUTRA"},
      {"no": 15, "nama": "BUNGA CITRA LESTARI"},
      {"no": 16, "nama": "CAHYA KIRANA DEWI"},
      {"no": 17, "nama": "CALVIN SAPUTRA WIJAYA"},
      {"no": 18, "nama": "CHANDRA WIGUNA NUGROHO"},
      {"no": 19, "nama": "CHELSEA AULIA RAMADHANI"},
      {"no": 20, "nama": "CHIKO RAMADHAN PUTRA"},
      {"no": 21, "nama": "CHRISTIAN SAPUTRA"},
      {"no": 22, "nama": "CINDY AULIA MAHARANI"},
      {"no": 23, "nama": "CITRA DEWI LESTARI"},
      {"no": 24, "nama": "DAFFA AL GHIFARI"},
      {"no": 25, "nama": "DAFFA PUTRA RAMADHAN"},
      {"no": 26, "nama": "DHANI AKBAR MAULANA"},
      {"no": 27, "nama": "DINDA AYU LESTARI"},
      {"no": 28, "nama": "DINARA AULIA MAHARANI"},
      {"no": 29, "nama": "DIONISIUS SATYA WICAKSANA"},
      {"no": 30, "nama": "DWIKI ARYA SAPUTRA"},
      {"no": 31, "nama": "EGI PRATAMA PUTRA"},
      {"no": 32, "nama": "EKA NURMALA SARI"},
      {"no": 33, "nama": "ELSA MAHARANI PUTRI"},
      {"no": 34, "nama": "ELVIRA NABILA PUTRI"},
      {"no": 35, "nama": "ELYSIA ANGGRAINI PUTRI"},
      {"no": 36, "nama": "ERLANGGGA WIJAYA PUTRA"}
    ]
  },
  {
    "kelas": "XI - 8",
    "siswa": [
      {"no": 1, "nama": "EVA NUR AZIZAH"},
      {"no": 2, "nama": "EVAN PRASETYO UTOMO"},
      {"no": 3, "nama": "FADHILAH NUR AZIZAH"},
      {"no": 4, "nama": "FAHMI ALAMSYAH PUTRA"},
      {"no": 5, "nama": "FAHREZI DWI PRASETYA"},
      {"no": 6, "nama": "FARHAN ADITYA NUGROHO"},
      {"no": 7, "nama": "FAZA ADITYA RAMADHAN"},
      {"no": 8, "nama": "FIKRI ALAMSYAH"},
      {"no": 9, "nama": "FIONA AULIA RAMADHANI"},
      {"no": 10, "nama": "FRISKA AULIA RAMADHANI"},
      {"no": 11, "nama": "GADING MAHESA PUTRA"},
      {"no": 12, "nama": "GENDIS AYU MAHARANI"},
      {"no": 13, "nama": "GHINA AULIA RAMADHANI"},
      {"no": 14, "nama": "GILANG ADITYA PRATAMA"},
      {"no": 15, "nama": "GISELLA PUTRI AULIA"},
      {"no": 16, "nama": "GITA MAHARANI SARI"},
      {"no": 17, "nama": "GITA PUSPITA AYU"},
      {"no": 18, "nama": "GUNTUR SAPUTRA WIJAYA"},
      {"no": 19, "nama": "HAFIZH AKBAR RAMADHAN"},
      {"no": 20, "nama": "HALIZA KIRANA PUTRI"},
      {"no": 21, "nama": "HANA FAUZIAH RAHMA"},
      {"no": 22, "nama": "HANIF ABDURRAHMAN"},
      {"no": 23, "nama": "HANIFAH NUR AZIZAH"},
      {"no": 24, "nama": "HANIYAH FAUZIAH"},
      {"no": 25, "nama": "HARIS FIRMANSYAH"},
      {"no": 26, "nama": "HENDRA WIJAYA KUSUMA"},
      {"no": 27, "nama": "IBRAHIM FATHURRAHMAN"},
      {"no": 28, "nama": "ILHAM RAMADHAN KURNIAWAN"},
      {"no": 29, "nama": "INDAH PERMATA SARI"},
      {"no": 30, "nama": "INDRA SAPUTRA WIJAYA"},
      {"no": 31, "nama": "INDRIANI SARI"},
      {"no": 32, "nama": "IQBAL FATHURRAHMAN"},
      {"no": 33, "nama": "IRA NOVITASARI"},
      {"no": 34, "nama": "ISKANDAR ZULKARNAIN"},
      {"no": 35, "nama": "JASON PRATAMA PUTRA"},
      {"no": 36, "nama": "JASMINE KIRANA PUTRI"}
    ]
  },
  {
    "kelas": "XII - 5",
    "siswa": [
      {"no": 1, "nama": "JESICA AULIA MAHARANI"},
      {"no": 2, "nama": "JIHAN FAUZIAH RAHMA"},
      {"no": 3, "nama": "JIHAN NABILA AZZAHRA"},
      {"no": 4, "nama": "JOKO SUSILO UTOMO"},
      {"no": 5, "nama": "JOVITA KIRANA DEWI"},
      {"no": 6, "nama": "KANIA SALSABILA PUTRI"},
      {"no": 7, "nama": "KANYA KIRANA DEWI"},
      {"no": 8, "nama": "KARTIKA AULIA RAHMA"},
      {"no": 9, "nama": "KARTIKA SARI DEWI"},
      {"no": 10, "nama": "KAYLA KIRANA MAHARANI"},
      {"no": 11, "nama": "KEANU PRATAMA PUTRA"},
      {"no": 12, "nama": "KEVIN ALEXANDER PUTRA"},
      {"no": 13, "nama": "KHALID AL FATIH"},
      {"no": 14, "nama": "LARAS AYU KINANTHI"},
      {"no": 15, "nama": "LARASATI AYU KINANTI"},
      {"no": 16, "nama": "LEO SAPUTRA WIJAYA"},
      {"no": 17, "nama": "LINTANG ADITYA PRADANA"},
      {"no": 18, "nama": "LIVIA KIRANA RAMADHANI"},
      {"no": 19, "nama": "LUCKY PRATAMA PUTRA"},
      {"no": 20, "nama": "LUKMAN HAKIM"},
      {"no": 21, "nama": "LUTHFI MAULANA HAKIM"},
      {"no": 22, "nama": "MAULANA MALIK IBRAHIM"},
      {"no": 23, "nama": "MAYA SARI ANGGRAINI"},
      {"no": 24, "nama": "MAYA ZAHRA AULIA"},
      {"no": 25, "nama": "MEILANI SARI PUTRI"},
      {"no": 26, "nama": "MILA NUR AZIZAH"},
      {"no": 27, "nama": "MITHA AULIA RAMADHANI"},
      {"no": 28, "nama": "MUHAMMAD ZAKI ZAIN"},
      {"no": 29, "nama": "MUTIARA HIKMAH RAMADHANI"},
      {"no": 30, "nama": "NABILA FITRIA RAMADHANI"},
      {"no": 31, "nama": "NADIA PUTRI RAHMAWATI"},
      {"no": 32, "nama": "NANDA PUTRI AULIA"},
      {"no": 33, "nama": "NATASHA AULIA PUTRI"},
      {"no": 34, "nama": "NAUFAL ARYA PRATAMA"},
      {"no": 35, "nama": "NAUFAL RAFI RAMADHAN"},
      {"no": 36, "nama": "NICHO SAPUTRA WIJAYA"}
    ]
  },
  {
    "kelas": "XII - 6",
    "siswa": [
      {"no": 1, "nama": "NICO ALEXANDER PUTRA"},
      {"no": 2, "nama": "OCHA KIRANA MAHARANI"},
      {"no": 3, "nama": "OKI SAPUTRA"},
      {"no": 4, "nama": "OLIVE KIRANA PUTRI"},
      {"no": 5, "nama": "OLIVIA SALSABILA PUTRI"},
      {"no": 6, "nama": "OMAR FARUQ ARRASYID"},
      {"no": 7, "nama": "OSCAR ANDREAS PUTRA"},
      {"no": 8, "nama": "OZAN RAMADHAN PUTRA"},
      {"no": 9, "nama": "PANDU WIGUNA SAPUTRA"},
      {"no": 10, "nama": "PRAMUDYA ADITYA PRATAMA"},
      {"no": 11, "nama": "PRATIWI NUR HASANAH"},
      {"no": 12, "nama": "PRISKA KIRANA MAHARANI"},
      {"no": 13, "nama": "PRITA AYU WULANDARI"},
      {"no": 14, "nama": "PUSPITA DEWI ANGGRAINI"},
      {"no": 15, "nama": "PUTRA ADITYA PRATAMA"},
      {"no": 16, "nama": "PUTRI AMELIA RAHMA"},
      {"no": 17, "nama": "QUEEN AULIA RAMADHANI"},
      {"no": 18, "nama": "QUEENA AULIA RAMADHANI"},
      {"no": 19, "nama": "QUINN AULIA RAMADHANI"},
      {"no": 20, "nama": "QORI ATHAYA ZAHRA"},
      {"no": 21, "nama": "RAFA ALVARO IBRAHIM"},
      {"no": 22, "nama": "RAFAEL SEBASTIAN PUTRA"},
      {"no": 23, "nama": "RAFI DARMA PUTRA"},
      {"no": 24, "nama": "RAKA SATRIA NUGRAHA"},
      {"no": 25, "nama": "RAMA ADITYA PRATAMA"},
      {"no": 26, "nama": "RANGGA SAPUTRA WIJAYA"},
      {"no": 27, "nama": "RENDI SAPUTRA WIJAYA"},
      {"no": 28, "nama": "RIZKY RAMADHAN PUTRA"},
      {"no": 29, "nama": "SABRINA KIRANA MAHARANI"},
      {"no": 30, "nama": "SALSABILA NUR AINI"},
      {"no": 31, "nama": "SALSHA KIRANA PUTRI"},
      {"no": 32, "nama": "SHEILA AULIA MAHARANI"},
      {"no": 33, "nama": "SHEREN AULIA PUTRI"},
      {"no": 34, "nama": "SINTA DEWI LESTARI"},
      {"no": 35, "nama": "SITI NURHALIZA"},
      {"no": 36, "nama": "SYAHRINI AULIA PUTRI"}
    ]
  },
  {
    "kelas": "XII - 7",
    "siswa": [
      {"no": 1, "nama": "TAMA WIJAYA KUSUMA"},
      {"no": 2, "nama": "TANIA AULIA RAMADHANI"},
      {"no": 3, "nama": "TASYA KIRANA PUTRI"},
      {"no": 4, "nama": "TAUFIK HIDAYATULLOH"},
      {"no": 5, "nama": "TEGAR ADITYA PRATAMA"},
      {"no": 6, "nama": "TEGUH PRASETYO WIBOWO"},
      {"no": 7, "nama": "TIARA KIRANA RAMADHANI"},
      {"no": 8, "nama": "TIO ADITYA PRATAMA"},
      {"no": 9, "nama": "UJANG SAPUTRA WIJAYA"},
      {"no": 10, "nama": "ULFA RAHMAWATI PUTRI"},
      {"no": 11, "nama": "ULANDARI PUSPITA SARI"},
      {"no": 12, "nama": "ULYA AZZAHRA"},
      {"no": 13, "nama": "UMAR FARUQ HAKIM"},
      {"no": 14, "nama": "UMI KALSUM AZZAHRA"},
      {"no": 15, "nama": "URSULA AULIA RAMADHANI"},
      {"no": 16, "nama": "UTARI PUSPITA SARI"},
      {"no": 17, "nama": "VALENTINO ROSSI PUTRA"},
      {"no": 18, "nama": "VANESSA AULIA PUTRI"},
      {"no": 19, "nama": "VANIA PUSPITA SARI"},
      {"no": 20, "nama": "VEGA PUTRI WIJAYA"},
      {"no": 21, "nama": "VERONICA AULIA PUTRI"},
      {"no": 22, "nama": "VICKY ARDIANSYAH PUTRA"},
      {"no": 23, "nama": "VINA AULIA RAHMAWATI"},
      {"no": 24, "nama": "VIONA AULIA MAHARANI"},
      {"no": 25, "nama": "WAHYU HIDAYATULLAH"},
      {"no": 26, "nama": "WAWAN SETIAWAN"},
      {"no": 27, "nama": "WENDY SAPUTRA WIJAYA"},
      {"no": 28, "nama": "WIDYA KIRANA PUTRI"},
      {"no": 29, "nama": "WINDA SARI PUSPITA"},
      {"no": 30, "nama": "WIRA ARDIANSYAH PUTRA"},
      {"no": 31, "nama": "WISNU WARDHANA"},
      {"no": 32, "nama": "WULAN PUSPITA SARI"},
      {"no": 33, "nama": "XAVIER PRATAMA PUTRA"},
      {"no": 34, "nama": "XENA KIRANA MAHARANI"},
      {"no": 35, "nama": "XENIA MAHARANI PUTRI"}
    ]
  }
];